info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
ticket:
  file: classpath:/tickets.csv
  chunk.size: 1
  poller:
    cron: '*/10 * * * * *'
    path: 'c:\\temp'
    fileMask: '*.csv'
  job:
    parameter: 'input.file.name'
  metrics:
    count: EXTERNAL
  queue: 'jms/ticket'
server:
  port: 8080
management:
  port: 8081
  address: 127.0.0.1
  security:
    enabled: true
    user:
      name: admin
      password: secret
    role: SUPERUSER
spring:
  batch:
    job:
      enabled: false
  jpa:
    show-sql: true
    generate-ddl: true
    properties.javax.persistence:
      sharedCache.mode: NONE
  h2.console.enabled: false
  datasource:
    url: jdbc:h2:file:~/ticketdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  activemq:
    in-memory: true
    broker-url: tcp://localhost:61616