ticket:
  file: classpath:/tickets.csv
  chunk.size: 1
  poller:
    cron: '*/10 * * * * *'
    path: 'c:\\temp'
    fileMask: '*.csv'
  job:
    parameter: 'input.file.name'
  metrics:
    count: EXTERNAL
server:
  port: 8080
management:
  port: 9001
  address: 127.0.0.1
spring:
  batch:
    job:
      enabled: false
  jpa:
    show-sql: true
    generate-ddl: true
    properties.javax.persistence:
      sharedCache.mode: NONE
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:~/ticketdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
#  jms:
#    jndi-name: java:/jms/ConnectionFactory
  activemq:
    in-memory: true
    broker-url: tcp://localhost:61616
